### ISSUE TITLE
Black and inaccessible floating windows

### ISSUE THREAD

**Issue by moritzschaefer** [emacs-exwm/exwm#19]
It happens to me once in a while that EXWM starts to fail to properly show floating windows (e.g. file save dialog). These then appear as black boxes (in the size of the dialog that's supposed to be there).
There is no way to interact with these dialogs (so I can also not make them tiling again), but I can kill the buffer, which makes them disappear (and also unfreeze the associated X application).

Unfortunately, once this happens the first time, emacs is "locked" in a state, in which this always happens to floating windows, so I need to restart Emacs to fix it.

Can I provide any debug information to pinpoint the issue?

**Comment by Stebalien** [comment]
By "save" dialog, I assume you mean an Emacs save dialog? EXWM is _supposed_ to run these functions in a subordinate Emacs process.

Or are you talking about other X applications (that's what it sounds like)? If so:

- Could you provide a screenshot of this happening? (if possible, just to make sure we don't end up talking past each other).
- Run `M-x exwm-debug`, reproduce the issue, then upload contents in the `*XELB-DEBUG*` buffer.

Finally, just for completeness, are you running a compositor (like picom)? I'm asking because "black windows" can also mean transparency issues.

Also note: there's more debugging instructions in https://github.com/emacs-exwm/exwm/wiki#how-to-report-a-bug if this isn't sufficient.

**Comment by moritzschaefer** [comment]
@Stebalien thanks for your response last week. I am still waiting for the issue to occur again, but when it does, I will provide all the suggested information.

**Comment by Stebalien** [comment]
Ok, got it. So the issue is floating windows.

What EXWM version are you using?

**Comment by moritzschaefer** [comment]
Yes, floating windows.

My EXWM version is `exwm-20231006.20000`

**Comment by moritzschaefer** [comment]
I worked around by forcing all windows to open in tiled mode. I'll reopen if it occurs again
