### ISSUE TITLE
Keyboard problems with Libreoffice

### ISSUE THREAD

**Issue by jaor** [emacs-exwm/exwm#27]
Hi. I am using exwm from melpa unstable, and the latest Libreoffice version in Debian Sid.

Since a couple months ago, opening documents in Libreoffice's Writer ends up blocking the keyboard in EXWM, sometimes to the point only the mouse works on any Emacs window. In those situations, exiting LO and clicking a couple of times in different emacs windows seems to restore reception of keyboard events, but a couple of times it was actually impossible. Other times the keyboard is not stolen everywhere, but only in the Writer's window, where trying any key gives rise to an error saying that the buffer is read-only, as if keystrokes were not being relayed to the X app.

Usually, the quickest way of triggering the problem is launching LibreOffice's Writer and pressing C-o to open a document: the non-writeable error is thrown and the keyboard stops working. Other times that works, but moving around a document, switching windows in Emacs and possibly opening other dialogs in LO eventually leads to the same problems.

As mentioned, this started happening a couple of months ago, after a long time of using LO in EXWM without any issue and no significant changes to my emacs config that I can remember. It's a bit complicated to remove that config of the equation, but I'll eventually get there. In the meantime, I thought I'd ask here in case anyone else has noticed similar problems.

Thanks!

**Comment by walseb** [comment]
Hi!

I'm having a similar issue several times per day. The mouse suddenly stops registering in the EXWM windows and I get the read-only error you describe. It never affects my keyboard however, and I don't use LibreOffice. I mostly use Firefox, Gimp, and Inkscape. I can't reproduce it reliably, and I haven't tried reproducing it with a bare-bones config due to the time it takes for it to happen. The only observation I have made is that it seems to happen most often when a lot of stuff is going on. 

As for solving it, a similar trick of clicking on the window a few times worked around 10% of the time for me, the rest of the time I had to restart Emacs to fix it which was very annoying. 

Eventually I figured out that if I restart my mouse, the issue is fixed without having to restart Emacs. So now, I simply run this whenever the problem occurs: `sudo modprobe -r psmouse; sudo modprobe psmouse;`.

Maybe you could try that with the keyboard instead of the mouse? Hope this helps!

Also, it would be interesting to know if anyone else is experiencing something similar to this. I thought I was the only one with issues like this, perhaps caused by some obscure X11 bug relating to my specific laptop GPU. It never happened in the years that I used my desktop PC.

**Comment by jaor** [comment]
thanks for the hint, glad to not being alone :) problem for me is that,
since it's the keyboard that becomes unresponsive, i cannot type that
command to restart the mouse :)

i forgot to add in my report that this happens to me both in emacs 29.2
and in recent emacs 30 compiled from the git master branch.

**Comment by walseb** [comment]
I see, so you can't even use your keyboard in Emacs buffers after the issue occurs? For me only X buffers were affected. Maybe you could bind the click action of an icon in your mode line to trigger that code. An emergency button. :)

**Comment by walseb** [comment]
I have had the same issue with some version of Emacs 28, Emacs 29.2, and I'm currently running Emacs 30.0.50. It all begun after I started using my T480, so my issue is probably hardware related to some degree.

**Comment by jaor** [comment]
i think i've discovered in my case the problems are due to my messing up
with window focus when using pdf-tools. i've got a package that updates
the echo area with tailored information (typically, bits that are put in
the modeline, such as chat trackers), with a "special" focus change when
moving away from a pdf-tools buffer (long story, it's an old bug
unrelated to exwm). if i don't have a pdf-view-mode buffer visible, or
disable the hack, my problems seem to disappear (my using pdf-tools
instead of docview-mode a couple of months ago maps my recollection of
when these problems started for me).

so, most problably unrelated to your case, Sebastian, I am afraid.

**Comment by walseb** [comment]
It's great that you solved it! What package is it in case I run into it? Maybe this should be closed then as it's not an issue with exwm.

**Comment by jaor** [comment]
@walseb it's some elisp code of my own that i haven't published in any elpa, so you're safe unless you follow my emacs config repo :)

closing!

**Comment by Stebalien** [comment]
@walseb can you open a new issue so we can debug?

**Comment by walseb** [comment]
> @walseb can you open a new issue so we can debug?

Hello! 

Thanks for your patience.

Do you think that would be useful? I don't have any means of reproducing it, so I'm not really sure it would be actionable in any way. But perhaps someone would have some idea for how to debug it.

What do you think?

**Comment by Stebalien** [comment]
I'm not sure, but I'm happy to try to rule it out. E.g., if clicking on Emacs windows (selecting text, etc.) still works but clicking on X windows doesn't, that indicates that it's not a hardware issue. Next, I'd pull up `xev` to see what the events look like (and xelb-debug will likely be pretty useful as well).

**Comment by walseb** [comment]
Hello! I apologize for the late reply.

Good idea, I will test `xev` next that next time it locks up.
