### ISSUE TITLE
Adrián is breaking `describe-package-1`

### ISSUE THREAD

**Issue by port19x** [emacs-exwm/exwm#78]
When trying to click on `exwm` or `xelb` in the package list (after running `package-list-packages`) I get the following error:

`describe-package-1: Wrong type argument: char-or-string-p, ("Adrián Medraño Calvo" . "adrian@medranocalvo.com")`

That's pretty funny. Not sure what you can do about it

**Comment by port19x** [comment]
Are you sure this is the multiple maintainers issue and not perhaps caused by emacs struggling with unicode?
For clarification, I'm using emacs 29.4 with the latest exwm and xelb from elpa-devel.

I'll check with emacs master just to be sure

**Comment by port19x** [comment]
Yep, you're right. It works with emacs 31, and probably emacs 30 as well

**Comment by minad** [comment]
This issue is also present in many other (also more popular) packages with multiple maintainers. I consider the issue wontfix from our side. Reducing the maintainer header to a single maintainer has downsides, e.g., the other maintainers won't get release notification mails from ELPA builder anymore.
